ketabgard/urls.py
# Create your views here.
from django.urls import path

from . import views

app_name = 'ketabgard'
urlpatterns = [
    path('<int:pk>/', views.book_profile.as_view(), name='book_profile'),
    path('list/', views.book_list.as_view(), name='book_list'),
    path('top/', views.book_top.as_view(), name='book_top'),
    
    path('list/add1/', views.assign_book_to_already_read_list.as_view(), name='add_to_already_read_list'),
    path('list/remove1/', views.unassign_book_to_already_read_list.as_view(), name='remove_from_already_read_list'),

    path('list/add2/', views.assign_book_to_reading_list.as_view(), name='add_to_reading_list'),
    path('list/remove2/', views.unassign_book_to_reading_list.as_view(), name='remove_from_reading_list'),

    path('list/add3/', views.assign_book_to_to_read_list.as_view(), name='add_to_to_read_list'),
    path('list/remove3/', views.unassign_book_to_to_read_list.as_view(), name='remove_from_to_read_list'),

]

matikan/urls.py
from django.contrib import admin
from django.urls import include, path
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('ketabgard.urls')),
    path('user/', include('sabte_ahval.urls')),
    path('', include('sabte_ahval.urls')),
    
]

sabte_ahval/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from .views import home, register

from . import views
from django.contrib.auth import views as auth_views
app_name = 'sabte_ahval'
urlpatterns = [
    path('', home),
    path('login/', auth_views.login),
    path('register/', register),
    path('<int:pk>/already_read/', views.already_read_list.as_view(), name='already_read'),
    path('<int:pk>/reading/', views.reading_list.as_view(), name='reading'),
    path('<int:pk>/to_read/', views.to_read_list.as_view(), name='to_read'),
    path('<int:pk>/', views.user_profile.as_view(), name='user_profile'),
    
]

sabte_ahval/models.py
from django.db import models
from django.contrib.auth.models import User
from ketabgard import models as ketabgard_models

class Comment(models.Model):
    text = models.CharField(max_length=1024)
    point = models.SmallIntegerField(choices=[(1,"⭐️"),(2,"⭐️⭐️"),(3,"⭐️⭐️⭐️")], blank=False, default=2)
    book = models.ForeignKey(ketabgard_models.Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.get_username()+" on "+ self.book.title + " : " + self.text + " ⭐️" + str(self.point)

sabte_ahval/forms.py
from django import forms
class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'نام کاربری',
        max_length = 32,
         widget=forms.TextInput(attrs={
            'class': 'form-control centre'
         
        })
    )
    email = forms.CharField(
        required = True,
        label = 'ایمیل',
        max_length = 64,
        widget=forms.TextInput(attrs={
            'class': 'form-control centre'
            
        })
    )
    password = forms.CharField(
        required = True,
        label = 'رمز عبور',
        max_length = 32,
        widget = forms.PasswordInput(attrs={
            'class': 'form-control'})
    )

    

sabte_ahval/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from .forms import UserRegistrationForm
from ketabgard import models as ketabgard_models
from django.urls import reverse

def home(request):
    return render(request, 'sabte_ahval/index.html')
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email =  userObj['email']
            password =  userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username = username, password = password)
                login(request, user)
                return HttpResponseRedirect(reverse('sabte_ahval:user_profile', args=(user.pk,)))
            else:
                return HttpResponse('Looks like a username with that email already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form' : form})

    

from django.views import generic

class already_read_list(generic.ListView):
    model = ketabgard_models.Book
    context_object_name = "books"
    template_name = 'sabte_ahval/already_read.html'

    def get_queryset(self):
        books=ketabgard_models.Book.objects.filter(already_read=self.request.user)
        return books
    
class reading_list(generic.ListView):
    model = ketabgard_models.Book
    context_object_name = "books"
    template_name = 'sabte_ahval/reading.html'

    def get_queryset(self):
        books=ketabgard_models.Book.objects.filter(reading=self.request.user)
        return books

class to_read_list(generic.ListView):
    model = ketabgard_models.Book
    context_object_name = "books"
    template_name = 'sabte_ahval/to_read.html'

    def get_queryset(self):
        books=ketabgard_models.Book.objects.filter(to_read=self.request.user)
        return books

class user_profile(generic.DetailView):
    """ showing user profile """
    model = User 
    template_name = 'sabte-ahval/profile.html'

   

sabte_ahval/templates/sabte_ahval/already_read.html
<!DOCTYPE html>
<html lang="fa">
<style>
    img {
        display: block;
        max-width: 100%;
        max-height: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        height: auto;
        width: auto;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }

    .centre {
        display: block;
        margin-left: auto;
        align-content: center;
        text-align: center;
        margin-right: auto;
    }

    .word-wrap {
        word-wrap: break-word;
    }

    div {

        border-radius: 10px;
     
      
    }
    .bg {
        /* The image used */
        background-image: url("https://www.norfolk.gov.uk/-/media/norfolk/images/homepage-carousel/library-books-1500-x-662.jpeg");
    
        /* Full height */
        height: 100%; 
    
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    } 
    @font-face { 
        font-family: Samim;
        src: url(https://cdn.rawgit.com/rastikerdar/sam-font/v2.0.1/dist/Samim.woff);
        font-weight: normal;
         }
    * {font-family: Samim;}
</style>

<head>
    <link href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" rel="stylesheet">
    <title>{{ book.title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body class="bg">
    <div class="container" >
        <div class="row row-eq-height centre">
            <div class="col-12">
            
                    <div class="form-group centre">
              
                    </div>
                
            </div>
        </div>
        <div class="row row-eq-height centre">
    {% if not books %}
        </div>
        <div class="row row-eq-height">
            <div class="col-12 centre">
                <h1 class="alert alert-danger">کتاب مورد نظر یافت نشد</h1>
            </div>
        </div>
    {% else %}
        <div class="col-12" style="background-color:#c3b8b2">
            <h1 >کتاب‌های خوانده شده</h1>
        </div>
    {% for book in books %} {% if forloop.counter0|divisibleby:3 %}
    </div>
    <div class="row row-eq-height">
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height" >
                    <div class="col-12" style="height: 20rem;">
                        <img src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{ book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height" >
                    <div class="col-12 " style="height: 20rem;">
                        <img src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height">
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
    {% endif %} {% endfor %} {% endif %}
    </div>
</body>

</html>

sabte_ahval/templates/sabte_ahval/index.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
  <!-- BASICS -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>ماتیکان</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'sabte_ahval/css/isotope.css' %}" media="screen" />
  <link rel="stylesheet" href="{% static 'sabte_ahval/js/fancybox/jquery.fancybox.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'sabte_ahval/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'sabte_ahval/css/bootstrap-theme.css' %}">
  <link rel="stylesheet" href="{% static 'sabte_ahval/css/style.css' %}">
  <!-- skin -->
  <link rel="stylesheet" href="{% static 'sabte_ahval/skin/default.css' %}">
  <!-- =======================================================
    Theme Name: Amoeba
    Theme URL: https://bootstrapmade.com/free-one-page-bootstrap-template-amoeba/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
  <section id="header" class="appear"></section>
  <div class="navbar navbar-fixed-top" role="navigation" data-0="line-height:100px; height:100px; background-color:rgba(0,0,0,0.3);" data-300="line-height:60px; height:60px; background-color:rgba(0,0,0,1);">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="fa fa-bars color-white"></span>
					</button>
        <h1><a class="navbar-brand" href="index.html" data-0="line-height:90px;" data-300="line-height:50px;">			ماتیکان
					</a></h1>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav" data-0="margin-top:20px;" data-300="margin-top:5px;">
          <li ><a href="#">درباره ما</a></li>
          <li><a href="user/register">ثبت نام</a></li>
          <li><a href="user/login">ورود</a></li>
          <li class="active"><a href="#">صفحه اول</a></li>
        </ul>
      </div>
      <!--/.navbar-collapse -->
    </div>
  </div>

  <section class="featured">
    <div class="container">
      <div class="row mar-bot40">
        <div class="col-md-6 col-md-offset-3">

          <div class="align-center">
            <i class="fa fa-flask fa-5x mar-bot20"></i>
            <h2 class="slogan">به ماتیکان خوش آمدید</h2>
            <p>ماتیکان مکانی برای دوستداران کتاب
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- services -->
  <section id="books" class="section pad-bot30 bg-white">
    <div class="container"> 
        <div class="row mar-bot60">
            <div class="col-lg-6">
              <div class="align-center">
       <h2><a href="book/list">لیست تمام کتاب‌ها</a></h2>
      </div>
    </div>
    <div class="row mar-bot60">
        <div class="col-lg-6">
          <div class="align-center">
   <h2><a href="book/top">لیست کتاب‌های پر‌بازدید</a></h2>
  </div>
</div>
    </div>
  </section>

  <!-- spacer section:testimonial -->
  <section id="testimonials" class="section" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="align-center">
            <div class="testimonial pad-top40 pad-bot40 clearfix">
              <h5>
                  خوشبخت، کسی است که به یکی از این دو چیز دسترسی دارد، یا کتاب های خوب یا دوستانی که اهل کتاب باشند
                  			</h5>
              <br/>
              <span class="author"><br/>
                <br/>
                 ویکتور هوگو</span>
            </div>

          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- about -->
  <section id="section-about" class="section appear clearfix">
    <div class="container">

      <div class="row mar-bot40">
        <div class="col-md-offset-3 col-md-6">
          <div class="section-header">
            <h2 class="section-heading animated" data-animation="bounceInUp">تیم ما</h2>
            <p> تیم ما متشکل از 4 دانشجوی رشته علوم کامپیوتر دانشگاه صنعتی امیرکبیر است که علاقه‌مند به فعالیت در زمینه طراحی و گسترش وب می‌باشد</p>
          </div>
        </div>
      </div>

      <div class="row align-center mar-bot40">
        <div class="col-md-3">
          <div class="team-member">
            <figure class="member-photo"><img src="{% static 'sabte_ahval/img/team/member2.jpg' %}" alt="" /></figure>
            <div class="team-detail">
              <h4>نازنین</h4>
             
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="team-member">
            <figure class="member-photo"><img src="{% static 'sabte_ahval/img/team/member1.jpg' %}" alt="" /></figure>
            <div class="team-detail">
              <h4>مومو</h4>
             </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="team-member">
            <figure class="member-photo"><img src="{% static 'sabte_ahval/img/team/member3.jpg' %}" alt="" /></figure>
            <div class="team-detail">
              <h4>عرفان</h4>
              </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="team-member">
            <figure class="member-photo"><img src="{% static 'sabte_ahval/img/team/member4.jpg' %}" alt="" /></figure>
            <div class="team-detail">
              <h4>مینو</h4>
              </div>
          </div>
        </div>
      </div>

    </div>
  </section>
  <!-- /about -->

  <!-- spacer section:stats -->
  <section id="parallax1" class="section pad-top40 pad-bot40" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="align-center pad-top40 pad-bot40">
        <blockquote class="bigquote color-white">کتاب، بزرگ‌ترین اختراع بشر است </blockquote>
        <p class="color-white">ویلیام شکسپیر</p>
      </div>
    </div>
  </section>

  <!-- contact -->
  <section id="section-contact" class="section appear clearfix">
    <div class="container">

      <div class="row mar-bot40">
        <div class="col-md-offset-3 col-md-6">
          <div class="section-header">
            <h2 class="section-heading animated" data-animation="bounceInUp">با ما در ارتباط باشید</h2>
            <p>لطفا به منظور افزایش کیفیت سایت نظرات و پیشنهادات خود را با ما در میان بگذارید</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="cform" id="contact-form">
            <div id="sendmessage">
              پیام شما ارسال شد. با تشکر
            </div>
            <div id="errormessage"></div>
            <form action="" method="post" role="form" class="contactForm">
              <div class="form-group">
                <label for="name">نام شما</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="نام" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validation"></div>
              </div>
              <div class="form-group">
                <label for="email">ایمیل شما</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="ایمیل" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validation"></div>
              </div>
              <div class="form-group">
                <label for="subject">موضوع</label>
                <input type="text" class="form-control" name="subject" id="subject" placeholder="موضوع" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validation"></div>
              </div>
              <div class="form-group">
                <label for="message">پیام</label>
                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us"></textarea>
                <div class="validation"></div>
              </div>

              <button type="submit" class="btn btn-theme pull-left">ارسال</button>
            </form>

          </div>
        </div>
        <!-- ./span12 -->
      </div>

    </div>
  </section>
  <!-- map -->
  <section id="section-map" class="clearfix">
    <div id="google-map" data-latitude="40.713732" data-longitude="-74.0092704"></div>
  </section>

  <section id="footer" class="section footer">
    <div class="container">
      <div class="row animated opacity mar-bot20" data-andown="fadeIn" data-animation="animation">
        <div class="col-sm-12 align-center">
          <ul class="social-network social-circle">
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>

      <div class="row align-center copyright">
        <div class="col-sm-12">
          <p>Copyright &copy; matikan</p>
          
        </div>
      </div>
    </div>

  </section>
  <a href="#header" class="scrollup"><i class="fa fa-chevron-up"></i></a>

  <script src="js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
  <script src="js/jquery.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.isotope.min.js"></script>
  <script src="js/jquery.nicescroll.min.js"></script>
  <script src="js/fancybox/jquery.fancybox.pack.js"></script>
  <script src="js/skrollr.min.js"></script>
  <script src="js/jquery.scrollTo.js"></script>
  <script src="js/jquery.localScroll.js"></script>
  <script src="js/stellar.js"></script>
  <script src="js/jquery.appear.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8HeI8o-c1NppZA-92oYlXakhDPYR7XMY"></script>
  <script src="js/main.js"></script>
  <script src="contactform/contactform.js"></script>
</body>

</html>

sabte_ahval/templates/sabte_ahval/reading.html
<!DOCTYPE html>
<html lang="fa">
<style>
    img {
        display: block;
        max-width: 100%;
        max-height: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        height: auto;
        width: auto;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }

    .centre {
        display: block;
        margin-left: auto;
        align-content: center;
        text-align: center;
        margin-right: auto;
    }

    .word-wrap {
        word-wrap: break-word;
    }

    div {

        border-radius: 10px;
     
    }
    .bg {
        /* The image used */
        background-image: url("https://www.norfolk.gov.uk/-/media/norfolk/images/homepage-carousel/library-books-1500-x-662.jpeg");
    
        /* Full height */
        height: 100%; 
    
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    } 
    @font-face { 
        font-family: Samim;
        src: url(https://cdn.rawgit.com/rastikerdar/sam-font/v2.0.1/dist/Samim.woff);
        font-weight: normal;
         }
    * {font-family: Samim;}
</style>

<head>
    <link href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" rel="stylesheet">
    <title>{{ book.title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body class="bg">
    <div class="container" >
        <div class="row row-eq-height centre">
            <div class="col-12">
            
                    <div class="form-group centre">
              
                    </div>
                
            </div>
        </div>
        <div class="row row-eq-height centre">
    {% if not books %}
        </div>
        <div class="row row-eq-height">
            <div class="col-12 centre">
                <h1 class="alert alert-danger">کتاب مورد نظر یافت نشد</h1>
            </div>
        </div>
    {% else %}
        <div class="col-12" style="background-color:#c3b8b2">
            <h1>کتاب‌های در حال مطالعه</h1>
        </div>
    {% for book in books %} {% if forloop.counter0|divisibleby:3 %}
    </div>
    <div class="row row-eq-height">
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height">
                    <div class="col-12" style="height: 20rem;">
                        <img src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{ book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height" >
                    <div class="col-12 " style="height: 20rem;">
                        <img src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
    {% endif %} {% endfor %} {% endif %}
    </div>
</body>

</html>

sabte_ahval/templates/sabte_ahval/to_read.html
<!DOCTYPE html>
<html lang="fa">
<style>
    img {
        display: block;
        max-width: 100%;
        max-height: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        height: auto;
        width: auto;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }

    .centre {
        display: block;
        margin-left: auto;
        align-content: center;
        text-align: center;
        margin-right: auto;
    }

    .word-wrap {
        word-wrap: break-word;
    }

    div {

        border-radius: 10px;
    }
    .bg {
        /* The image used */
        background-image: url("https://www.norfolk.gov.uk/-/media/norfolk/images/homepage-carousel/library-books-1500-x-662.jpeg");
    
        /* Full height */
        height: 100%; 
    
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    } 
    @font-face { 
        font-family: Samim;
        src: url(https://cdn.rawgit.com/rastikerdar/sam-font/v2.0.1/dist/Samim.woff);
        font-weight: normal;
         }
    * {font-family: Samim;}
</style>

<head>
    <link href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" rel="stylesheet">
    <title>{{ book.title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body class="bg">
    <div class="container" >
        <div class="row row-eq-height centre">
            <div class="col-12">
            
                    <div class="form-group centre">
              
                    </div>
                
            </div>
        </div>
        <div class="row row-eq-height centre">
    {% if not books %}
        </div>
        <div class="row row-eq-height">
            <div class="col-12 centre">
                <h1 class="alert alert-danger">کتاب مورد نظر یافت نشد</h1>
            </div>
        </div>
    {% else %}
        <div class="col-12" style="background-color:#c3b8b2">
            <h1 >کتاب هایی که میخوام بخونم</h1>
        </div>
    {% for book in books %} {% if forloop.counter0|divisibleby:3 %}
    </div>
    <div class="row row-eq-height">
        <div class="col-4">
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height" >
                    <div class="col-12" style="height: 20rem;">
                        <img src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{ book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height" >
                    <div class="col-12 " style="height: 20rem;">
                        <img src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
    {% endif %} {% endfor %} {% endif %}
    </div>
</body>

</html>