ketabgard/urls.py
# Create your views here.
from django.urls import path

from . import views

app_name = 'ketabgard'
urlpatterns = [
    path('<int:pk>/', views.book_profile.as_view(), name='book_profile'),
    path('list/', views.book_list.as_view(), name='book_list'),
    path('top/', views.book_top.as_view(), name='book_top'),
    
    path('list/add1/', views.assign_book_to_already_read_list.as_view(), name='add_to_already_read_list'),
    path('list/remove1/', views.unassign_book_to_already_read_list.as_view(), name='remove_from_already_read_list'),

    path('list/add2/', views.assign_book_to_reading_list.as_view(), name='add_to_reading_list'),
    path('list/remove2/', views.unassign_book_to_reading_list.as_view(), name='remove_from_reading_list'),

    path('list/add3/', views.assign_book_to_to_read_list.as_view(), name='add_to_to_read_list'),
    path('list/remove3/', views.unassign_book_to_to_read_list.as_view(), name='remove_from_to_read_list'),

]

matikan/urls.py
from django.contrib import admin
from django.urls import include, path
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('ketabgard.urls')),
    path('user/', include('sabte_ahval.urls')),
    path('', include('sabte_ahval.urls')),
    
]

sabte_ahval/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from .views import home, register

from . import views
from django.contrib.auth import views as auth_views
app_name = 'sabte_ahval'
urlpatterns = [
    path('', home),
    path('login/', auth_views.login),
    path('register/', register),
    path('<int:pk>/already_read/', views.already_read_list.as_view(), name='already_read'),
    path('<int:pk>/reading/', views.reading_list.as_view(), name='reading'),
    path('<int:pk>/to_read/', views.to_read_list.as_view(), name='to_read'),
    path('<int:pk>/', views.user_profile.as_view(), name='user_profile'),
    
]

sabte_ahval/models.py
from django.db import models
from django.contrib.auth.models import User
from ketabgard import models as ketabgard_models

class Comment(models.Model):
    text = models.CharField(max_length=1024)
    point = models.SmallIntegerField(choices=[(1,"⭐️"),(2,"⭐️⭐️"),(3,"⭐️⭐️⭐️")], blank=False, default=2)
    book = models.ForeignKey(ketabgard_models.Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.get_username()+" on "+ self.book.title + " : " + self.text + " ⭐️" + str(self.point)

sabte_ahval/forms.py
from django import forms
class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'نام کاربری',
        max_length = 32,
         widget=forms.TextInput(attrs={
            'class': 'form-control centre'
         
        })
    )
    email = forms.CharField(
        required = True,
        label = 'ایمیل',
        max_length = 64,
        widget=forms.TextInput(attrs={
            'class': 'form-control centre'
            
        })
    )
    password = forms.CharField(
        required = True,
        label = 'رمز عبور',
        max_length = 32,
        widget = forms.PasswordInput(attrs={
            'class': 'form-control'})
    )

    

sabte_ahval/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from .forms import UserRegistrationForm
from ketabgard import models as ketabgard_models
from django.urls import reverse

def home(request):
    return render(request, 'sabte_ahval/index.html')
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email =  userObj['email']
            password =  userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username = username, password = password)
                login(request, user)
                return HttpResponseRedirect(reverse('sabte_ahval:user_profile', args=(user.pk,)))
            else:
                return HttpResponse('Looks like a username with that email already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form' : form})

    

from django.views import generic

class already_read_list(generic.ListView):
    model = ketabgard_models.Book
    context_object_name = "books"
    template_name = 'sabte_ahval/already_read.html'

    def get_queryset(self):
        books=ketabgard_models.Book.objects.filter(already_read=self.request.user)
        return books
    
class reading_list(generic.ListView):
    model = ketabgard_models.Book
    context_object_name = "books"
    template_name = 'sabte_ahval/reading.html'

    def get_queryset(self):
        books=ketabgard_models.Book.objects.filter(reading=self.request.user)
        return books

class to_read_list(generic.ListView):
    model = ketabgard_models.Book
    context_object_name = "books"
    template_name = 'sabte_ahval/to_read.html'

    def get_queryset(self):
        books=ketabgard_models.Book.objects.filter(to_read=self.request.user)
        return books

class user_profile(generic.DetailView):
    """ showing user profile """
    model = User 
    template_name = 'sabte-ahval/profile.html'

   

sabte_ahval/templates/sabte-ahval/profile.html
<!DOCTYPE html>
<html lang="fa">
<style>
                
        body, html {
            height: 100%;
            margin: 0;
        }
        
        .bg {
            /* The image used */
            background-image: url("https://www.2rph.org.au/2rph_admin/resources/program-lunchtime-book-1-w843h360.jpg");
            
            /* Full height */
            height: 100%; 
        
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        } 

    body {
        background-color: beige;
    }

    img {
        
        margin-left: auto;
        margin-right: auto;

        margin-top: 50px;
        margin-bottom: 50px;
        
     
    }
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
    }
    
    li {
        float: left;
    }
    
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }
    
    li a:hover {
        background-color: #111;
    }

    .centre {
        display: block;
        margin-left: auto;
        align-content: center;
        text-align: center;
        margin-right: auto;
    }
    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }

    .word-wrap {
        word-wrap: break-word;
    }

    h5,
    h2,
    h6 {
        text-align: right;
        direction: rtl;
    }

    div {
        border-radius: 25px;
     
    }
</style>

<head>
    <link href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" rel="stylesheet">
    <title>{{ book.title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body   class="bg">
    <div class="container" >
        <div class="row row-eq-height" class="text-right">
                <ul>
                        <li><a  href="{% url 'ketabgard:book_list' %}">لیست کتاب ها</a></li>
                        
                      </ul>
        </div>
      <div class="row row-eq-height" class="text-right">
            <div class="col-4 centre" >
            
            </div>
            <div class="col-4" >
                <div class="row row-eq-height" class="text-right" ></div>
                <div class="row row-eq-height" class="text-right">
                       <div class="col-8 centre" >
                                <img src="http://funnypicture.org/wallpaper/2015/05/funny-cat-books-7-high-resolution-wallpaper.jpg" class="img-thumbnail">
                        </div>
                    
                </div>
                <div class="row row-eq-height" class="text-right">
                        <div class="col-12 centre" style="background-color: #c3b8b2">
                                  {{ user.username }}
                        </div>
                </div>
            </div>
            <div class="col-4" >
                    <div class="row row-eq-height" class="text-right" >
                           
                            <div class="col-8 centre" style="background-color:#b2bec3">
                                    <a  href="{% url 'sabte_ahval:already_read' pk=user.pk%}">
                                   <h6>
                                            
                                            خوندم
                                   </h6> 
                                    </a>
                           </div>
                           
                    </div>  
                    <div class="row row-eq-height" class="text-right" >
                         
                            <div class="col-8 centre" style="background-color:#b2bec3"> 
                                    <a  href="{% url 'sabte_ahval:reading' pk=user.pk%}">
                                            <h6>
                                                     
                                                     دارم میخونم
                                            </h6> 
                                             </a>
                            </div>
                            
                            
                    </div>
                    <div class="row row-eq-height" class="text-right" >
                            
                            <div class="col-8 centre" style="background-color:#b2bec3" >
                                    <a  href="{% url 'sabte_ahval:to_read' pk=user.pk%}">
                                            <h6>
                                                     
                                               میخوام بخونم
                                            </h6> 
                                             </a>
                            </div>
                            
                    </div>
            </div>
        </div>
    </div>

</body>

</html>