ketabgard/urls.py
# Create your views here.
from django.urls import path

from . import views

app_name = 'ketabgard'
urlpatterns = [
    path('<int:pk>/', views.book_profile.as_view(), name='book_profile'),
    path('list/', views.book_list.as_view(), name='book_list'),
    path('top/', views.book_top.as_view(), name='book_top'),
    
    path('list/add1/', views.assign_book_to_already_read_list.as_view(), name='add_to_already_read_list'),
    path('list/remove1/', views.unassign_book_to_already_read_list.as_view(), name='remove_from_already_read_list'),

    path('list/add2/', views.assign_book_to_reading_list.as_view(), name='add_to_reading_list'),
    path('list/remove2/', views.unassign_book_to_reading_list.as_view(), name='remove_from_reading_list'),

    path('list/add3/', views.assign_book_to_to_read_list.as_view(), name='add_to_to_read_list'),
    path('list/remove3/', views.unassign_book_to_to_read_list.as_view(), name='remove_from_to_read_list'),

]

matikan/urls.py
from django.contrib import admin
from django.urls import include, path
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('ketabgard.urls')),
    path('user/', include('sabte_ahval.urls')),
    path('', include('sabte_ahval.urls')),
    
]

sabte_ahval/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from .views import home, register

from . import views
from django.contrib.auth import views as auth_views
app_name = 'sabte_ahval'
urlpatterns = [
    path('', home),
    path('login/', auth_views.login),
    path('register/', register),
    path('<int:pk>/already_read/', views.already_read_list.as_view(), name='already_read'),
    path('<int:pk>/reading/', views.reading_list.as_view(), name='reading'),
    path('<int:pk>/to_read/', views.to_read_list.as_view(), name='to_read'),
    path('<int:pk>/', views.user_profile.as_view(), name='user_profile'),
    
]

ketabgard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation

from hitcount.models import HitCount, HitCountMixin

class Author(models.Model):
    name = models.CharField(max_length=1024, default="UNKNOWN")
    def __str__(self):
        return self.name


class Translator(models.Model):
    name = models.CharField(max_length=1024, default="UNKNOWN")

class Publisher(models.Model):
    name = models.CharField(max_length=1024, default="UNKNOWN")
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=1024, default="UNKNOWN")
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=1024)
    picture_path = models.CharField(max_length=2048, default="")
    description = models.CharField(max_length=4096, null=True)
    author = models.ForeignKey(Author, on_delete=models.SET_DEFAULT, default=None, null=True)
    translator = models.ForeignKey(Translator, on_delete=models.SET_DEFAULT, default=None, null=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.SET_DEFAULT, default=None, null=True)
    category = models.ManyToManyField(Category)
    already_read = models.ManyToManyField(User, related_name="already_read")
    reading = models.ManyToManyField(User, related_name="reading")
    to_read = models.ManyToManyField(User, related_name="to_read")
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    def __str__(self):
        return self.title

ketabgard/forms.py
from django import forms
from sabte_ahval import models
from .models import Author, Publisher, Category


class SearchForm(forms.Form):
    """ search title in book list form """
    search_title = forms.CharField(
        label="نام کتاب",
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control centre',
            'placeholder': 'نام کتاب'
        }),
        required=False
    )
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(), empty_label="همه نویسندگان", required=False)
    publisher = forms.ModelChoiceField(
        queryset=Publisher.objects.all(), empty_label="همه ناشران", required=False)
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(), widget= forms.CheckboxSelectMultiple, required=False)


class CommentForm(forms.ModelForm):
    action_url = ""
    method = "post"
    class Meta:
        model = models.Comment
        fields = ["text", "point"]
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'نقد'
            }),
            'point': forms.RadioSelect
        }

ketabgard/views.py
""" views for ketabgard """
from django.views import generic, View
from django.urls import reverse
from .forms import SearchForm, CommentForm
from .models import Book
from sabte_ahval import models as sabte_ahval_models
from django.http import HttpResponse,HttpResponseRedirect
from hitcount.views import HitCountDetailView

class book_profile(HitCountDetailView):
    """ showing book profile """
    model = Book
    template_name = 'ketabgard/profile.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        """ set contex vars and adding seach form to list """
        context = super().get_context_data(**kwargs)
        # getting all comments for current book
        context["comments"] = sabte_ahval_models.Comment.objects.filter(
            book=self.object)
        #get number of 0 points
        context["0_points"] = sabte_ahval_models.Comment.objects.filter(
            book=self.object).filter(point=0).count()
        #get number of 1 points
        context["1_points"] = sabte_ahval_models.Comment.objects.filter(
            book=self.object).filter(point=1).count()
        #get number of 2 points
        context["2_points"] = sabte_ahval_models.Comment.objects.filter(
            book=self.object).filter(point=2).count()   
        # getting self comment if exists
        context["self_comment"] = context["comments"].filter(
            user_id=self.request.user.id)

        if self.object.already_read.filter(pk=self.request.user.id).exists():
            context["already_read"] = True
        else:
            context["already_read"]= False

        if self.object.reading.filter(pk=self.request.user.id).exists():
            context["reading"] = True
        else:
            context["reading"]= False

        if self.object.to_read.filter(pk=self.request.user.id).exists():
            context["to_read"] = True
        else:
            context["to_read"]= False

        # sending comment form
        context["form"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        """ saving comment if anything sent with post """
        new_comment = sabte_ahval_models.Comment(
            book=self.get_object(),
            user=request.user,
            text=request.POST.get('text'),
            point=request.POST.get('point'),
        )
        new_comment.save()
        self.object = self.get_object()  # isnt there any more clear way?
        # rendering normal book profile
        return super().render_to_response(self.get_context_data())

class assign_book_to_already_read_list(View):
    def post(self, request, *args, **kwargs):
        book_pk = self.request.POST.get("book_pk")
        Book.objects.get(pk=book_pk).already_read.add(self.request.user)
        return HttpResponseRedirect(reverse("ketabgard:book_profile",kwargs={'pk':book_pk}))
    
class unassign_book_to_already_read_list(View):
    def post(self, request, *args, **kwargs):
        book_pk = self.request.POST.get("book_pk")
        Book.objects.get(pk=book_pk).already_read.remove(self.request.user)
        return HttpResponseRedirect(reverse("ketabgard:book_profile",kwargs={'pk':book_pk}))

class assign_book_to_reading_list(View):
    def post(self, request, *args, **kwargs):
        book_pk = self.request.POST.get("book_pk")
        Book.objects.get(pk=book_pk).reading.add(self.request.user)
        return HttpResponseRedirect(reverse("ketabgard:book_profile",kwargs={'pk':book_pk}))
    
class unassign_book_to_reading_list(View):
    def post(self, request, *args, **kwargs):
        book_pk = self.request.POST.get("book_pk")
        Book.objects.get(pk=book_pk).reading.remove(self.request.user)
        return HttpResponseRedirect(reverse("ketabgard:book_profile",kwargs={'pk':book_pk}))

class assign_book_to_to_read_list(View):
    def post(self, request, *args, **kwargs):
        book_pk = self.request.POST.get("book_pk")
        Book.objects.get(pk=book_pk).to_read.add(self.request.user)
        return HttpResponseRedirect(reverse("ketabgard:book_profile",kwargs={'pk':book_pk}))
    
class unassign_book_to_to_read_list(View):
    def post(self, request, *args, **kwargs):
        book_pk = self.request.POST.get("book_pk")
        Book.objects.get(pk=book_pk).to_read.remove(self.request.user)
        return HttpResponseRedirect(reverse("ketabgard:book_profile",kwargs={'pk':book_pk}))

class book_list(generic.ListView):
    """ list books also support search with GET """
    model = Book
    context_object_name = "books"
    template_name = 'ketabgard/list.html'

    def get_context_data(self, **kwargs):
        """ set contex vars and adding seach form to list """
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm()
        if self.request.GET.get("search_title"):
            context["form"].fields['search_title'].widget.attrs["value"] = self.request.GET.get("search_title")
        if self.request.GET.get("author"):
            context["form"].fields['author'].initial = self.request.GET.get("author")
        if self.request.GET.get("publisher"):
            context["form"].fields['publisher'].initial = self.request.GET.get("publisher")
        if self.request.GET.getlist("categories"):
            context["form"].fields['categories'].initial = self.request.GET.getlist("categories")
        return context

    def get_queryset(self):
        """ prepare books and filter them if there is GET on search_title """
        result = super().get_queryset()
        search_title = self.request.GET.get("search_title")
        author = self.request.GET.get("author")
        publisher = self.request.GET.get("publisher")
        cats = self.request.GET.getlist("categories")
        if search_title:
            for word in search_title.split():
                result = result.filter(title__icontains=word)
        if author:
            result = result.filter(author=author)
        if publisher:
            result = result.filter(publisher=publisher)
        if cats:
            for cat in cats:
                result = result.filter(category__in=cat)
        return result

class book_top(generic.ListView):
    """ show top 6 books """
    model = Book
    context_object_name = "books"
    template_name = 'ketabgard/top.html'

    def get_queryset(self):
        result = super().get_queryset()
        result = result.order_by("-hit_count_generic__hits")[:6]
        return result

ketabgard/templates/ketabgard/list.html
<!DOCTYPE html>
<html lang="fa">
<style>
    img {
        display: block;
        max-width: 100%;
        max-height: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        height: auto;
        width: auto;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
    }
    
    li {
        float: left;
    }
    
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }
    
    li a:hover {
        background-color: #111;
    }
    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }

    .centre {
        display: block;
        margin-left: auto;
        align-content: center;
        text-align: center;
        margin-right: auto;
    }

    .word-wrap {
        word-wrap: break-word;
    }

    div {

        border-radius: 10px;
     
        
    }
    @font-face { 
        font-family: Samim;
        src: url(https://cdn.rawgit.com/rastikerdar/sam-font/v2.0.1/dist/Samim.woff);
        font-weight: normal;
         }
    * {font-family: Samim;}
             
    body, html {
        height: 100%;
        margin: 0;
    }
    
    .bg {
        /* The image used */
        background-image: url("https://www.norfolk.gov.uk/-/media/norfolk/images/homepage-carousel/library-books-1500-x-662.jpeg");
    
        /* Full height */
        height: 100%; 
    
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    } 

</style>

<head>
    <link href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" rel="stylesheet">
    <title>{{ book.title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body class="bg" >
    <div class="container" >
        <div class="row row-eq-height centre">
            <div class="col-4 ">
                    <div class="row row-eq-height" class="text-right">
                    <ul>
                            <li><a  href="{% url 'sabte_ahval:user_profile'  pk=user.pk %}">صفحه‌ی پروفایل</a></li>
                            
                          </ul>
                          </div>
            </div>
            <div class="col-8"  style="background-color:#2b2222">

                <form class="form-inline">
                    <div class="form-group centre">
                            {{ form.search_title }}
                            {{ form.author }}
                            {{ form.publisher }}
                    </div>
                    <div style="color:white" class="form-group centre">
                        {% for cat in  form.categories%}
                        {{ cat }}
                        {% endfor %}
                        <input type="submit" class="btn btn-default" value="🔍">
                    </div>
                </form>
            </div>
        </div>
        
        <div class="row row-eq-height centre">
    {% if not books %}
        </div>
        <div class="row row-eq-height">
            <div class="col-12 centre">
                <h1 class="alert alert-danger">کتاب مورد نظر یافت نشد</h1>
            </div>
        </div>
    {% else %}
        <div class="col-12" style="background-color:#c3b8b2">
            <h1><b>کتاب‌ها</b></h1>
        </div>
    {% for book in books %} {% if forloop.counter0|divisibleby:3 %}
    </div>
    <div class="row row-eq-height">
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height" >
                    <div class="col-12" style="height: 20rem; ">
                        <img class="img-thumbnail" src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{ book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height" >
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-4" >
            <a href="{% url 'ketabgard:book_profile' book.id %}">
                <div class="row row-eq-height">
                    <div class="col-12 " style="height: 20rem;">
                        <img class="img-thumbnail" src="{{ book.picture_path }}" alt="{{ book.title }}">
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 centre" style="background-color:#b2bec3">
                        {{book.title }}
                    </div>
                </div>
            </a>
            <div class="row row-eq-height">
                <div class="col-12 centre" style="background-color:#b2bec3">
                    {{ book.author.name }}
                </div>
            </div>
        </div>
    {% endif %} {% endfor %} {% endif %}
    </div>
</body>

</html>

ketabgard/templates/ketabgard/profile.html
<!DOCTYPE html>
<html lang="fa">
        <head>
                <link href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" rel="stylesheet">
                <title>{{ book.title }}</title>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                
             
               
            
            </head>
<style>
               
        body, html {
            height: 100%;
            margin: 0;
        }
        
        .bg {
            /* The image used */
            background-image: url("https://rozenbergdentalnyc.com/wp-content/uploads/2014/10/book-table-close-up-photo-wallpaper-1680x1050.jpg");
            
            /* Full height */
            height: 100%; 
        
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        } 

    body {
        background-color: beige;
    }

    img {
        display: block;
        max-width: 100%;
        max-height: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        height: auto;
        width: auto;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .row-eq-height {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
    }

    .word-wrap {
        word-wrap: break-word;
    }

    h5,
    h2,
    h4,
    h6 {
        text-align: right;
        direction: rtl;
    }

    div {
        border-radius: 25px;
       
    }
    .m{
        width:125px;

    }
    @font-face { 
        font-family: Samim;
        src: url("https://cdn.rawgit.com/rastikerdar/sam-font/v2.0.1/dist/Samim.woff");
        font-weight: normal;
         }
    * {font-family: Samim;}
</style>



<body  class="bg">
    <div class="container" >
        <div class="row row-eq-height" class="text-right">
            <div class="col-8" >
                <div class="row row-eq-height" >
                    <div class="col-12" style="background-color:#c3b8b2">
                        <h2><b>
                                {{ book.title }}
                        </b>
                            

                        </h2>

                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-6"  >
                        <canvas id="myChart" width="400" height="400"></canvas>
                    </div>
                    <div class="col-6"  >
                        <div class="row row-eq-height"  >
                            <div class="col-12" style="background-color:#b2bec3">
                                <h4>
                                    {{ book.author.name}}
                                </h4>
                            </div>
                        </div>
                        <div class="row row-eq-height" >
                            <div class="col-12" style="background-color:#b2bec3">
                                <h4>
                                    مترجم: {{ book.translator.name}}
                                </h4>
                            </div>
                        </div>
                        <div class="row row-eq-height" >
                            <div class="col-12" style="background-color:#b2bec3">
                                <h4>
                                    نشر: {{ book.publisher.name }}
                                </h4>
                            </div>
                        </div>
                        <div class="row row-eq-height" >
                            <div class="col-12" style="background-color:#b2bec3">
                                <h4>
                                    موضوع: {% for cat in book.category.all %} {{ cat.name }}, {% endfor %}
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-eq-height" >
                    <div class="col-12 word-wrap" style="background-color:#b2bec3">
                        <h6>
                            {{ book.description}}
                        </h6>
                    </div>
                </div>
                {# temprory showing self comment #}
                    {# if user was logged in and doesnt comment in past and also read the book, comment form will be show #}
                    {% if user.is_authenticated and not self_comment.exists and already_read %}
                    <form action="{{ form.action_url }}" method="{{ form.method }}">
                        <div class="row row-eq-height" >
                            <div class="col-8" style="background-color:#dfe6e9">
                                {{ form.text }}
                            </div>
                            <div class="col-4" style="background-color:#dfe6e9">
                            {% for point in form.point %}
                                <div class="radio">
                                    {{ point }}
                                </div>
                            {% endfor %}
                                {% csrf_token %}
                                <input type="submit" class="btn btn-default" value="💬">
                            </div>
                    </div>
                </form>
                {% endif %}
                {% for comment in comments reversed%}
                <div class="row text-right">
                        {% if comment.user.first_name %}
                        <div class="col-10" style="background-color:#dfe6e9">{{ comment.text }} </div>                        
                        <div class="col-2" style="background-color:#dfe6e9">
                            <b>{{ comment.user.first_name }}</b>
                        </div> 
                        {% else %}
                        <div class="col-10" style="background-color:#dfe6e9">{{ comment.text }} </div>                          
                        <div class="col-2" style="background-color:#dfe6e9">
                            <b>{{ comment.user.username }} </b>
                        </div> 
                        {% endif %}
                </div>
                {% endfor %}
            </div>
            <div class="col-4" >
                <img class="rounded mx-auto d-block img-thumbnail" margin="auto" src="{{ book.picture_path }}" alt="{{ book.title }}">
                <div class="row">
                {% if not already_read %}
                <form action="{% url 'ketabgard:add_to_already_read_list' %}" method="POST">
                    <input type="hidden" name="book_pk" value="{{ book.id }}"> {% csrf_token %}
                    <button type="submit" class="btn btn-success btn-md m" >خواندم</button>
                </form>
                {% else %}
                <form action="{% url 'ketabgard:remove_from_already_read_list' %}" method="POST">
                    <input type="hidden" name="book_pk" value="{{ book.id }}"> {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-md m">نخواندم</button>
                    {% endif %}
                </form>
                {% if not reading %}
                <form action="{% url 'ketabgard:add_to_reading_list' %}" method="POST">
                    <input type="hidden" name="book_pk" value="{{ book.id }}"> {% csrf_token %}
                    <button type="submit" class="btn btn-warning btn-md m">دارم میخونم</button>
                </form>
                {% else %}
                <form action="{% url 'ketabgard:remove_from_reading_list' %}" method="POST">
                    <input type="hidden" name="book_pk" value="{{ book.id }}"> {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-md m">انصراف از مطالعه </button>
                    {% endif %}
                </form>
                {% if not to_read %}
                <form action="{% url 'ketabgard:add_to_to_read_list' %}" method="POST">
                    <input type="hidden" name="book_pk" value="{{ book.id }}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-md m">میخوام بخونم</button>
                </form>
                    {% else %}
                <form action="{% url 'ketabgard:remove_from_to_read_list' %}" method="POST">
                    <input type="hidden" name="book_pk" value="{{ book.id }}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-md m">انصراف</button>
                    {% endif %}
                </form>
            </div> 
            </div>

        </div>
    </div>
</body>
<script>
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [1, 2, 3],
            datasets: [{
                label: 'نظرات کاربران',
                data: [
                    {{ 1_points }},
            {{ 2_points }},
                    {{ 3_points }}
                        ],
    backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)'
    ],
        borderColor: [
            'rgba(255,99,132,1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
        ],
            borderWidth: 1
                }]
            },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
        });
</script>

</html>